function showRecipe(kartyaId) {
    const kartya = document.getElementById(kartyaId);
    const receptek = {
        kartya1: "<strong>Hozzávalók:</strong><p>3 gerezd fokhagyma,1 db bagett,2 ek olívaolaj,1 fej salottahagyma,300g paradicsom,só,frissen őrölt fekete bors,1 marék bazsalikom</p><strong>Elkészítés:</strong><p>A bruchetta elkészítéséhez megtisztítjuk a fokhagymagerezdeket. A bagettet felszeleteljük. Felforrósítjük egy serpenyőben az olívaolaj kb. felét, és körbepirítunk rajta 2 db fokhagymagerezdet. Hagyjuk kihűlni, majd bedörzsöljük velük a bagettszeleteket. Nagyon finomra aprítjuk a maradék fokhagymát és a megtisztított salottát. A megmosott paradicsomot (piros és sárga vegyesen) apróra kockázzuk, majd kis lyukú szűrőben hagyjuk csepegni 10-15 percig. Ezután összekeverjük a kétféle hagymával és a megmaradt olívaolajjal, majd sózzuk, borsozzuk. A leöblített bazsalikomlevelek kb. egyharmadát félretesszük a tálaláshoz, a többit felaprítjuk, és a paradicsomos-hagymás elegyhez forgatjuk. A zöldséges keveréket a bagettszeletekre halmozzuk, majd a megmaradt bazsalikomlevelekkel díszítve kínáljuk.</p>",
        kartya2: "<strong>Hozzávalók:</strong><p>0.5 tk olaj, 1 tk vaj, 3 db tojás, 1 csip só</p><strong>Elkészítés:</strong><p>Egy serpenyőt közepes lángon melegíteni kezdünk. Beleöntjük az olajat, majd hozzáadjuk a vajat. Amíg a vaj felhabzik, a tojásokat egy keverőtálba öntjük, sózzuk, villával kissé felverjük (nem kell, hogy teljesen elkeveredjen a sárgája a fehérjével).A keveréket a habzó vajra öntjük, és körkörös mozdulatokkal keverve megsütjük. Ügyeljünk arra, hogy ne süssük szárazra (3 db tojás esetén nagyjából 1-2 perc a sütési idő).Végül ízlés szerint megszórhatjuk egy kevés őrölt pirospaprikával vagy akár sajttal. Pirítóssal, vagy friss kenyérrel tálaljuk.</p>",
        kartya3: "<strong>Hozzávalók:</strong><p>2 közepes db paradicsom, 4 kis db gomba, 2 ek vaj, 4 szelet bacon, 25 dkg főzőkolbász (4 kisebb grillkolbász), só ízlés szerint, bors ízlés szerint, 2 db tojás, 30 dkg paradicsomos babkonzerv, 4 szelet toast kenyér</p><strong>Elkészítés:</strong><p>Félbávágjuk a paradicsomokat és a gombákat, majd száraz grillserpenyőben mindkét oldalukat odapirítjuk. Félretesszük. Pici vajat dobunk a serpenyőbe és megpirítjuk rajta a szalonnaszeleteket, valamint a grillkolbászkákat. Sózzuk-borsozzuk és alaposan meggrillezzük őket. Sima aljú serpenyőre váltunk, picike vajat olvasztunk benne, majd megsütjük a tükörtojásokat. A kész tojásokat tányérra szedjük, majd a paradicsomos babot is felmelegítjük a serpenyőben. A kenyérszeleteket megpirítjuk és háromszög alakúra vágjuk (átlósan kettévágjuk). Egy nagy tányérra halmozzuk a reggeli minden alkotóelemét és egy nagy bögre tejes tea társaságában fogyasztjuk.</p>",
        kartya4: "<strong>Hozzávalók:</strong><p>2 db 30 cm-es tortilla lap, 8 szelet gépsonka (kb. 100 g), 8 db tojás, só, bors, 6 szál snidling, ½ db kígyóuborka (200 g/db), 1 db paradicsom (120 g/db), 1 db hónapos retek</p><strong>Elkészítés:</strong><p>A ham and eggs tortillakosár elkészítésének első lépéseként a tortilla lapokból egy 12 cm-es pogácsaszaggatóval kiszúrunk 8 db-ot. Ezeket a korongokat belenyomjuk a muffin sütőforma mélyedéseibe. Belehajtjuk a sonkákat, beleütünk mindegyikbe 1 db tojást, sózzuk, borsozzuk, és betesszük sülni a 180 fokra melegített sütőbe 15-20 percre. Ha megsültek a tojások, kiemeljük a formából őket, megszórjuk finomra vágott snidlinggel és a szeletelt zöldségekkel tálaljuk.</p>",
        kartya5: "<strong>Hozzávalók:</strong><p>3 dl tej, 3 evőkanál zabpehely, méz</p><strong>Elkészítés:</strong><p>A zabkása alaprecept elkészítéséhez egy kisebb, nyeles edénybe öntjük a tejet, majd belekanalazzuk a zabpelyhet, és 5-10 percet állni hagyjuk. Ha megdagadt a zabpehely, felrakjuk a tűzhelyre, és közepes lángon, állandó kevergetés mellett 5-10 perc alatt krémesre főzzük. Ha elkészült, a tűzről lehúzva, fedő alatt pihentetjük a kész zabkását még néhány percig, majd ízlés szerint mézzel, cukorral vagy más édesítőszerrel ízesítjük.</p>",
        kartya6: "<strong>Hozzávalók:</strong><p>3 db tojás, 0.3 csokor snidling, só ízlés szerint, bors ízlés szerint, 1 dkg vaj</p><strong>Elkészítés:</strong><p>A tojásokat egy mélyebb tálba ütjük. Villával jól felverjük úgy, hogy habos legyen - teljesen össze kell törni, nem szabad, hogy a fehérje egyben maradjon, mert kicsapódik sütéskor. A snidlinget apróra vágjuk, hozzáadjuk a tojáshoz, sózzuk, borsozzuk. A serpenyőt előmelegítjük. Ha már jó forró, akkor adjuk hozzá a vajat. Ha felolvadt és kicsit habos, de még nem barna, akkor beleöntjük a tojást. Várunk egy percet, míg kicsit megszilárdul, majd óvatosan huzigatni kezdjük, hogy mindenhol átsüljön, de krémes maradjon. A serpenyőt kicsit megbillentjük az egyik irányba, hogy a folyékony massza nagy része oda folyjon. Így tartjuk, majd ha már eléggé megszilárdult, a vékonyabb oldalt ráhajtjuk, és a serpenyőből kivéve azonnal tálaljuk.</p>",
        kartya7: "<strong>Hozzávalók:</strong><p>225 g finomliszt, 1 db tojás, 3 dl tej, 1 csomag sütőpor, 3 evőkanál cukor, 1 csomag vaníliás cukor, 1 késhegynyi fahéj, 1 evőkanál napraforgó olaj</p><strong>Elkészítés:</strong><p>Az összes hozzávalót beletesszük a turmixba, és alaposan összemixeljük. Érdemes 2 részletben hozzáadni a tejet és a lisztet, így egyszerűbb, hatékonyabb. Felforrósítunk és beolajozunk egy teflon serpenyőt. A tésztakeverékből 2-3 korongot csorgatunk bele. A turmix kiöntője segítségével egyszerű adagolni. Aranybarnára sütjük mindkét oldalát. Ízlés szerint fogyaszthatjuk mézzel, mogyorókrémmel, olvasztott csokival, lekvárral, juharsziruppal.</p>",
        kartya8: "<strong>Hozzávalók:</strong><p>4 szelet toast kenyér, 2 teáskanál vaj, 4 szelet sajt, 1 db paradicsom, 1 marék rukkola</p><strong>Elkészítés:</strong><p>A rukkolát és a paradicsomot megmossuk és szárazra törlünk. A paradicsomot felkarikázzuk. 2 szelet kenyeret megkenünk a vajjal, mindegyikre teszünk 2 szelet sajtot, majd néhány szelet paradicsomot és rukkolát ízlés szerint. A szendvicseket befedjük a maradék kenyérrel, majd melegszendvicssütőben 2-3 perc alatt készre sütjük. Félbevágva tálaljuk.</p>",
        kartya9: "<strong>Hozzávalók:</strong><p>8 szelet kenyér, 4 db tojás, 3 evőkanál főzőtejszín, só ízlés szerint, 4 dl napraforgó olaj</p><strong>Elkészítés:</strong><p>A bundáskenyérhez érdemes kissé szikkadtabb fehér típusú kenyeret használni. Tegyük fel az olajat lassan melegedni egy serpenyőben. Szeleteljük fel a kenyeret ízlés szerinti vastagságúakra. A kenyér nagyságához megfelelő edényben verjük fel a tojásokat a tejszínnel és a sóval. Mártsuk bele mindkét oldalát a tojásba. A vastagabb szeleteket hagyjuk tovább benne, majd tegyük félre kissé lecsöpögni. 170-180°C közötti hőmérsékleten érdemes sütni a bundáskenyeret, így nem fogja nagyon megszívni magát olajjal, és nem is ég meg hirtelen. Süssük pár percig mindkét oldalát, amíg szép aranybarna lesz. Az elkészült bundáskenyereket szedjük ki, és csepegtessük le egyből papírtörlőn. Jó étvágyat!</p>",
    };
    kartya.dataset.originalContent = kartya.innerHTML;
    kartya.innerHTML = `
        <div class="kartyaRecept">
            <h2>Recept</h2>
            <p>${receptek[kartyaId]}</p>
            <button onclick="hideRecipe('${kartyaId}')">Vissza</button>
        </div>
    `;
}

function hideRecipe(kartyaId) {
    const kartya = document.getElementById(kartyaId);
    kartya.innerHTML = kartya.dataset.originalContent;
}
